import React from 'react';

const TermsAndConditions = () => {
  return (
    <div className="max-w-4xl mx-auto px-8 py-24">
      <h1 className="text-4xl font-black mb-8">Terms & Conditions</h1>
      
      <div className="space-y-8 text-slate-300 leading-relaxed">
        <p>Last updated: March 10, 2026</p>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">1. Acceptance of Terms</h2>
          <p>By accessing and using Verdiq ("the Service"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the Service.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">2. Description of Service</h2>
          <p>Verdiq provides AI-powered music analysis, editorial reviews, and synthesized podcast generation. The Service utilizes third-party artificial intelligence models (such as Google Gemini) to process audio and text inputs provided by the user.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">3. User Accounts and Credits</h2>
          <ul className="list-disc pl-6 space-y-2 text-slate-400">
            <li>You must create an account to use certain features of the Service.</li>
            <li>The Service operates on a credit-based system. Credits must be purchased to generate reviews, publish to the magazine, or edit existing reviews.</li>
            <li><strong>No Refunds:</strong> All sales of credits are final. We do not offer refunds for purchased credits, whether used or unused, except where required by law.</li>
            <li>Credits do not expire as long as your account remains active.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">4. User Content and Intellectual Property</h2>
          <ul className="list-disc pl-6 space-y-2 text-slate-400">
            <li><strong>Your Ownership:</strong> You retain all ownership rights to the original audio files, lyrics, and images you upload ("User Content"). Verdiq claims no copyright over your original music.</li>
            <li><strong>License to Process:</strong> By uploading User Content, you grant Verdiq a worldwide, non-exclusive, royalty-free license to use, reproduce, and process the content solely for the purpose of providing the Service (e.g., generating the AI review and podcast).</li>
            <li><strong>Generated Content:</strong> You own the rights to the AI-generated text and podcast audio produced from your User Content. You may use this generated content for your own promotional purposes.</li>
            <li><strong>Magazine Publishing:</strong> If you choose to publish your review to the Verdiq Magazine, you grant us a non-exclusive, worldwide, royalty-free license to display, distribute, and promote that specific review and associated audio on our platform and marketing channels.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">5. Disclaimer of Warranties</h2>
          <p className="mb-4">THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. VERDIQ MAKES NO WARRANTIES, EXPRESSED OR IMPLIED, AND HEREBY DISCLAIMS AND NEGATES ALL OTHER WARRANTIES INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF INTELLECTUAL PROPERTY OR OTHER VIOLATION OF RIGHTS.</p>
          <p><strong>AI-Generated Opinions:</strong> The reviews and podcasts generated by Verdiq are created by artificial intelligence. They do not represent the opinions, beliefs, or endorsements of Verdiq, its owners, or its employees. The AI's analysis is subjective and for entertainment and promotional purposes only.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">6. Limitation of Liability</h2>
          <p className="uppercase font-bold text-sm tracking-wider mb-2">Please read carefully</p>
          <p>IN NO EVENT SHALL VERDIQ, ITS OWNERS, DIRECTORS, EMPLOYEES, OR SUPPLIERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM:</p>
          <ul className="list-disc pl-6 space-y-2 text-slate-400 mt-4">
            <li>Your access to or use of or inability to access or use the Service.</li>
            <li>Any conduct or content of any third party on the Service.</li>
            <li>Any content obtained from the Service, including any negative, inaccurate, or offensive AI-generated reviews or podcasts.</li>
            <li>Unauthorized access, use or alteration of your transmissions or content.</li>
          </ul>
          <p className="mt-4">You specifically acknowledge that Verdiq shall not be liable for the subjective nature of the AI-generated reviews, and you waive any right to pursue legal action against Verdiq for defamation, libel, or emotional distress arising from the AI's analysis of your music.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">7. Indemnification</h2>
          <p>You agree to defend, indemnify and hold harmless Verdiq and its licensee and licensors, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees), resulting from or arising out of a) your use and access of the Service, or b) a breach of these Terms.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">8. Changes to Terms</h2>
          <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.</p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-white mb-4">9. Contact Us</h2>
          <p>If you have any questions about these Terms, please contact us at:</p>
          <p className="mt-2 text-emerald-500 font-bold">verdiqmag@gmail.com</p>
        </section>
      </div>
    </div>
  );
};

export default TermsAndConditions;
